# Generated by Django 5.2.6 on 2025-10-23 05:05

import django.db.models.deletion
import django.utils.timezone
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '用户资料', 'verbose_name_plural': '用户资料'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='邮箱已验证'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_password_change',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后密码修改时间'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_verified',
            field=models.BooleanField(default=False, verbose_name='手机已验证'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='qq_openid',
            field=models.CharField(blank=True, max_length=100, verbose_name='QQ OpenID'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wechat_openid',
            field=models.CharField(blank=True, max_length=100, verbose_name='微信 OpenID'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weibo_uid',
            field=models.CharField(blank=True, max_length=100, verbose_name='微博 UID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.avatar_upload_path, validators=[users.models.validate_avatar_size], verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='个人简介'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_distance',
            field=models.CharField(blank=True, help_text='例如：5公里、半马、全马等', max_length=50, verbose_name='偏好距离'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='running_experience',
            field=models.CharField(choices=[('beginner', '初级跑者 (0-1年)'), ('intermediate', '中级跑者 (1-3年)'), ('advanced', '高级跑者 (3年以上)'), ('professional', '专业运动员')], default='beginner', max_length=20, verbose_name='跑步经验'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('user_agent', models.TextField(verbose_name='用户代理')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='登录时间')),
                ('login_type', models.CharField(choices=[('password', '密码登录'), ('qq', 'QQ登录'), ('wechat', '微信登录'), ('weibo', '微博登录')], default='password', max_length=20, verbose_name='登录方式')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '登录历史',
                'verbose_name_plural': '登录历史',
                'ordering': ['-login_time'],
            },
        ),
    ]
