# Generated by Django 5.2.6 on 2025-10-22 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0003_videoupload_end_time_videoupload_start_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='分析标题')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True, verbose_name='分析时间')),
                ('duration', models.FloatField(verbose_name='视频时长(秒)')),
                ('analyzed_frames', models.IntegerField(verbose_name='分析帧数')),
                ('cadence', models.FloatField(blank=True, null=True, verbose_name='步频(步/分钟)')),
                ('speed', models.FloatField(blank=True, null=True, verbose_name='速度(km/h)')),
                ('stride_length', models.FloatField(blank=True, null=True, verbose_name='步幅(米)')),
                ('ground_contact_time', models.FloatField(blank=True, null=True, verbose_name='触地时间(ms)')),
                ('vertical_oscillation', models.FloatField(blank=True, null=True, verbose_name='垂直振幅(cm)')),
                ('issues_count', models.IntegerField(default=0, verbose_name='问题数量')),
                ('high_severity_issues', models.IntegerField(default=0, verbose_name='严重问题')),
                ('medium_severity_issues', models.IntegerField(default=0, verbose_name='中等问题')),
                ('low_severity_issues', models.IntegerField(default=0, verbose_name='轻微问题')),
                ('analysis_quality', models.CharField(choices=[('excellent', '优秀'), ('good', '良好'), ('fair', '一般'), ('poor', '较差')], default='good', max_length=20, verbose_name='分析质量')),
                ('tags', models.JSONField(blank=True, null=True, verbose_name='标签')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('video_upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analysis.videoupload', verbose_name='视频上传记录')),
            ],
            options={
                'verbose_name': '分析历史记录',
                'verbose_name_plural': '分析历史记录',
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='ComparisonItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.analysishistory', verbose_name='分析记录')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ComparisonSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='对比会话名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('analyses', models.ManyToManyField(through='history.ComparisonItem', to='history.analysishistory', verbose_name='分析记录')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '对比会话',
                'verbose_name_plural': '对比会话',
            },
        ),
        migrations.AddField(
            model_name='comparisonitem',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.comparisonsession', verbose_name='对比会话'),
        ),
        migrations.CreateModel(
            name='ProgressTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_date', models.DateField(verbose_name='跟踪日期')),
                ('feeling', models.CharField(choices=[('excellent', '非常好'), ('good', '良好'), ('fair', '一般'), ('poor', '较差'), ('pain', '有疼痛')], max_length=20, verbose_name='主观感受')),
                ('training_notes', models.TextField(blank=True, verbose_name='训练记录')),
                ('improvements_noticed', models.BooleanField(default=False, verbose_name='是否感受到改进')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.analysishistory', verbose_name='分析记录')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '进度跟踪',
                'verbose_name_plural': '进度跟踪',
                'ordering': ['-tracking_date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='comparisonitem',
            unique_together={('session', 'analysis')},
        ),
    ]
