# Generated by Django 5.2.6 on 2025-10-23 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparisonsession',
            name='analyses',
        ),
        migrations.RemoveField(
            model_name='comparisonsession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='progresstracking',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='progresstracking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='analysishistory',
            name='analysis_quality',
        ),
        migrations.RemoveField(
            model_name='analysishistory',
            name='cadence',
        ),
        migrations.RemoveField(
            model_name='analysishistory',
            name='ground_contact_time',
        ),
        migrations.RemoveField(
            model_name='analysishistory',
            name='high_severity_issues',
        ),
        migrations.RemoveField(
            model_name='analysishistory',
            name='low_severity_issues',
        ),
        migrations.RemoveField(
            model_name='analysishistory',
            name='medium_severity_issues',
        ),
        migrations.RemoveField(
            model_name='analysishistory',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='analysishistory',
            name='speed',
        ),
        migrations.RemoveField(
            model_name='analysishistory',
            name='stride_length',
        ),
        migrations.RemoveField(
            model_name='analysishistory',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='analysishistory',
            name='vertical_oscillation',
        ),
        migrations.DeleteModel(
            name='ComparisonItem',
        ),
        migrations.DeleteModel(
            name='ComparisonSession',
        ),
        migrations.DeleteModel(
            name='ProgressTracking',
        ),
    ]
