# Generated by Django 5.2.6 on 2025-10-21 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pose_data', models.JSONField(blank=True, null=True)),
                ('mesh_data', models.JSONField(blank=True, null=True)),
                ('analysis_image', models.ImageField(blank=True, null=True, upload_to='analysis_results/')),
                ('cadence', models.FloatField(blank=True, null=True)),
                ('stride_length', models.FloatField(blank=True, null=True)),
                ('ground_contact_time', models.FloatField(blank=True, null=True)),
                ('vertical_oscillation', models.FloatField(blank=True, null=True)),
                ('issues', models.JSONField(blank=True, null=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analysis.videoupload')),
            ],
        ),
    ]
