# Generated by Django 5.2.6 on 2025-10-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='overall_metrics',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoupload',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoupload',
            name='fps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoupload',
            name='frame_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
