# Generated by Django 5.2.6 on 2025-10-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_analysisresult_overall_metrics_videoupload_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoupload',
            name='end_time',
            field=models.FloatField(blank=True, help_text='分析结束时间（秒）', null=True),
        ),
        migrations.AddField(
            model_name='videoupload',
            name='start_time',
            field=models.FloatField(default=0, help_text='分析开始时间（秒）'),
        ),
    ]
