# Generated by Django 5.2.6 on 2026-03-11 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_videoupload_end_time_videoupload_start_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisresult',
            options={'ordering': ['-analyzed_at']},
        ),
        migrations.AlterModelOptions(
            name='videoupload',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='videoupload',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='videoupload',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videoupload',
            name='progress_message',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='videoupload',
            name='task_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='video',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_result', to='analysis.videoupload'),
        ),
    ]
