# Generated by Django 5.2.6 on 2026-03-11 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_alter_analysisresult_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoupload',
            name='task_id',
        ),
    ]
